//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int ID { get; set; }
        public int ID_Street { get; set; }
        public int Home_Number { get; set; }
        public int HomeIndex { get; set; }
    
        public virtual Streets Streets { get; set; }
        public virtual ICollection<Order> Order { get; set; }
    }
}
