//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Product_Order = new HashSet<Product_Order>();
        }
    
        public int ID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime DeliverDate { get; set; }
        public int ID_Address { get; set; }
        public int ID_User { get; set; }
        public int Code { get; set; }
        public int ID_Status { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Status Status { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<Product_Order> Product_Order { get; set; }
    }
}
