//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Streets
    {
        public Streets()
        {
            this.Address = new HashSet<Address>();
        }
    
        public int ID { get; set; }
        public int ID_City { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Address> Address { get; set; }
        public virtual City City { get; set; }
    }
}
